spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: vectors

logging:
  pattern:
    console: "%d{HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"


langchain4j:
  embeddingModel:
    provider: OPEN_AI
    openAi:
      api-key: ${OPENAI_API_KEY}
      modelName: text-embedding-ada-002
      temperature: 0.1
      timeout: PT99S
      logRequests: true
      logResponses: true
  chatModel:
    provider: OPEN_AI
    openAi:
      api-key: ${OPENAI_API_KEY}
      modelName: gpt-3.5-turbo-16k
      temperature: 0.1
      timeout: PT999S
      logRequests: true
      logResponses: true